spring:
  application:
    name: securityservice
  datasource:
    url: jdbc:postgresql://localhost:5433/security
    username: security
    password: security
  flyway:
    schemas:
      - public
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/security
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: criptos-service client
            client-secret: IFOV7MyHA5Ibhvo8beY8N4ikfHJ5wgXo
            scope:
              - openid
              - criptos-service_client_scope
              - microprofile-jwr
