spring:
  application:
    name: securityservice

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/security
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: security-app
            client-secret: WsHUVZpKjhoMwXjHE6MMrt9HUBsvF6Fa
            scope:
              - openid
              - security_service
              - microprofile-jwr
