spring:
  application:
    name: userService
  datasource:
    url: jdbc:postgresql://localhost:5432/userService_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

