spring:
  application:
    name: documentService
  datasource:
    url: jdbc:postgresql://localhost:6541/documentService_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

logging:
    level:
      root: INFO
server:
  port: 9091

