spring:
  application:
    name: rabbitMqServer
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
    template:
      routing-key: testRoutingKey
      exchange: testExchange
    virtual-host: host
server:
  port: 9090
