version: "3.9"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: security
      POSTGRES_USER: security
      POSTGRES_PASSWORD: security
    ports:
      - "5433:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
        - './config/keycloak/import:/opt/keycloak/data/import'
    ports:
        - '8082:8080'
    command: start-dev --import-realm
