CREATE TABLE IF NOT EXISTS documents(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255) NOT NULL,
    content bytea[] NOT NULL,
    signature_id BIGINT NOT NULL REFERENCES signatures(id),
    creater_name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created TIMESTAMP NOT NULL,
    CONSTRAINT pk_document PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS signatures(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    signer_content bytea[] NOT NULL,
    created TIMESTAMP NOT NULL,
    document_id BIGINT NOT NULL REFERENCES documents(id),
    CONSTRAINT pk_signatures PRIMARY KEY(id)
)