CREATE TABLE IF NOT EXISTS signers(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    firstname VARCHAR(100),
    lastname VARCHAR(100),
    phone VARCHAR(20),
    public_key VARCHAR(1024) NOT NULL,
    private_key VARCHAR(2048) NOT NULL
);

CREATE TABLE IF NOT EXISTS documents(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    title VARCHAR(100) NOT NULL UNIQUE,
    content BYTEA NOT NULL,
    signature BYTEA,
    algorithm VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    signer_id BIGINT NOT NULL REFERENCES signers(id)
);



Drop table signers;
Drop table documents;